// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8o7557vYK6EpSHXtQaBXJ-gVMONHAggg',
    appId: '1:702456873384:web:0d9943df26f7f38309dd9d',
    messagingSenderId: '702456873384',
    projectId: 'scholarchat-ab428',
    authDomain: 'scholarchat-ab428.firebaseapp.com',
    storageBucket: 'scholarchat-ab428.appspot.com',
    measurementId: 'G-JNMT2DL6PT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl8u30PSCSJIy1w4lKvlPmuVt01R-I58c',
    appId: '1:702456873384:android:fa91d9f857479bad09dd9d',
    messagingSenderId: '702456873384',
    projectId: 'scholarchat-ab428',
    storageBucket: 'scholarchat-ab428.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHiW_BWzZFYxn42eKw8XNbV1kZmT--6Ks',
    appId: '1:702456873384:ios:734c893d4d36cff809dd9d',
    messagingSenderId: '702456873384',
    projectId: 'scholarchat-ab428',
    storageBucket: 'scholarchat-ab428.appspot.com',
    iosBundleId: 'com.example.scholarChat',
  );
}
